stages:
  - build

services:
  - name: docker:dind
    command:
      - "--experimental"

variables:
  DOCKER_BUILDKIT: "1"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_CLI_EXPERIMENTAL: enabled

.docker: &docker
  stage: build
  image: docker:latest
  only:
    - main
    - schedules
  retry: 2
  script:
    # Install docker buildx.
    - export BUILDX_VERSION=$(wget --spider -S "https://github.com/docker/buildx/releases/latest" 2>&1 | grep -m 1 'Location' | tr '/' ' ' | awk '{ print $8; }')
    - mkdir -p ~/.docker/cli-plugins
    - wget -qO ~/.docker/cli-plugins/docker-buildx "https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-$BUILDX_ARCH"
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    # Create docker context.
    - docker context create tls-environment
    # Load QEMU emulation layers.
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    # Login to GitLab Docker registry.
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # Create builder instance.
    - docker buildx create --use tls-environment --driver docker-container --name multiarch-builder
    # Bootstrap builder instance.
    - docker buildx inspect --bootstrap
    # Build, tag and push image image.
    - docker buildx build --push --platform $PLATFORMS -t $CI_REGISTRY_IMAGE:latest-$TAG .
    # Logout from GitLab Docker registry.
    - docker logout $CI_REGISTRY

build-docker-amd64:
  variables:
    BUILDX_ARCH: amd64
    PLATFORMS: linux/amd64
    TAG: amd64
  <<: *docker

build-docker-arm32v7:
  variables:
    BUILDX_ARCH: arm-v7
    PLATFORMS: linux/arm/v7
    TAG: arm32v7
  tags:
    - arm32v7
  <<: *docker

build-docker-arm64v8:
  variables:
    BUILDX_ARCH: arm64
    PLATFORMS: linux/arm64
    TAG: arm64v8
  tags:
    - arm64v8
  <<: *docker
