stages:
  - build

.buildkit: &buildkit
  stage: build
  image:
    name: moby/buildkit:rootless
    entrypoint: [ "sh", "-c" ]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  script:
    # Add container registry credentials.
    - |
      mkdir -m 700 -p ~/.docker
      cat << EOF > ~/.docker/config.json
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
    # Build and push container image.
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --output type=image,name=$CI_REGISTRY_IMAGE/$ARCH,push=true \
          --import-cache type=registry,ref=$CI_REGISTRY_IMAGE/$ARCH \
          --export-cache type=inline
    # Remove container registry credentials.
    - rm ~/.docker/config.json

build-docker-amd64:
  extends: .buildkit
  variables:
    ARCH: amd64

build-docker-arm32v7:
  extends: .buildkit
  variables:
    ARCH: arm32v7
  tags:
    - arch=arm32v7

build-docker-arm64v8:
  extends: .buildkit
  variables:
    ARCH: arm64v8
  tags:
    - arch=arm64v8
